apiVersion: v1
kind: Service
metadata:
  name: backend-external-study-kafka-service
spec:
  ports:
    - port: 9092

---

apiVersion: v1
kind: Endpoints
metadata:
  name: backend-external-study-kafka-service
subsets:
  - addresses:
      - ip: 192.168.0.14
    ports:
      - port: 9000
