
apiVersion: v1
kind: Service
metadata:
  name: backend-study-external-mysql-service
spec:
  ports:
    - port: 3306

---

apiVersion: v1
kind: Endpoints
metadata:
  name: backend-study-external-mysql-service
subsets:
  - addresses:
      - ip: 192.168.0.14
    ports:
      - port: 13306
